2024-04-28 12:08:17.433331: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-04-28 12:12:47.970069: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-04-28 12:12:48.484983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:48.489000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:25:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:48.493010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:81:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:48.497002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:48.497024: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-04-28 12:12:48.501016: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2024-04-28 12:12:48.501047: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2024-04-28 12:12:48.503162: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2024-04-28 12:12:48.503726: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-04-28 12:12:48.504398: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-04-28 12:12:48.505528: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2024-04-28 12:12:48.505914: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2024-04-28 12:12:48.534469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1, 2, 3
2024-04-28 12:12:48.534815: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-28 12:12:49.045226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:49.046659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:25:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:49.048074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:81:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:49.049562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA A40 computeCapability: 8.6
coreClock: 1.74GHz coreCount: 84 deviceMemorySize: 44.35GiB deviceMemoryBandwidth: 648.29GiB/s
2024-04-28 12:12:49.060622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1, 2, 3
2024-04-28 12:12:49.060663: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-04-28 12:12:50.565649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-04-28 12:12:50.565696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1 2 3 
2024-04-28 12:12:50.565703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N Y Y Y 
2024-04-28 12:12:50.565708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   Y N Y Y 
2024-04-28 12:12:50.565712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 2:   Y Y N Y 
2024-04-28 12:12:50.565716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 3:   Y Y Y N 
2024-04-28 12:12:50.581865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 43454 MB memory) -> physical GPU (device: 0, name: NVIDIA A40, pci bus id: 0000:01:00.0, compute capability: 8.6)
2024-04-28 12:12:50.583976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 43454 MB memory) -> physical GPU (device: 1, name: NVIDIA A40, pci bus id: 0000:25:00.0, compute capability: 8.6)
2024-04-28 12:12:50.586006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 43454 MB memory) -> physical GPU (device: 2, name: NVIDIA A40, pci bus id: 0000:81:00.0, compute capability: 8.6)
2024-04-28 12:12:50.588034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 43454 MB memory) -> physical GPU (device: 3, name: NVIDIA A40, pci bus id: 0000:c1:00.0, compute capability: 8.6)
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1d (Conv1D)              (None, 2199, 32)          544       
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 1099, 32)          0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 1098, 64)          4160      
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 549, 64)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 548, 128)          16512     
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 274, 128)          0         
_________________________________________________________________
flatten (Flatten)            (None, 35072)             0         
_________________________________________________________________
dropout (Dropout)            (None, 35072)             0         
_________________________________________________________________
dense (Dense)                (None, 128)               4489344   
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 774       
=================================================================
Total params: 4,511,334
Trainable params: 4,511,334
Non-trainable params: 0
_________________________________________________________________
'tuple' object has no attribute 'X'
Traceback (most recent call last):
  File "/home/tuo72868/ece_8527_final/cnn/src/train.py", line 97, in <module>
    
  File "/home/tuo72868/ece_8527_final/cnn/src/train.py", line 85, in main
    model.fit(train=train, dev=dev, batch=16)
  File "/home/tuo72868/ece_8527_final/cnn/src/util/CNN.py", line 53, in evaluate
    loss, accuracy = self.model.evaluate(ds.X, ds.y)
AttributeError: 'tuple' object has no attribute 'X'
